export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const REGISTER_NEW_USER = "REGISTER_NEW_USER";
export const GET_CIRCULARS = "GET_CIRCULARS";
export const CREATE_CIRCULAR = "CREATE_CIRCULAR";